name: Consul jobs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'rocks/consul/rockcraft.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build the rock
      uses: canonical/craft-actions/rockcraft-pack@main
      with:
        path: rocks/consul/
        verbosity: debug
    - name: Upload rock
      uses: actions/upload-artifact@v4
      with:
        name: consul-rock
        path: |
          rocks/consul/consul_*_amd64.rock
  validate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built Consul rock
        uses: actions/download-artifact@v4
        with:
          name: consul-rock
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Upload Consul Rock to Docker image registry
        run: |
          sudo rockcraft.skopeo --insecure-policy \
          copy oci-archive:consul_v1.19.2_amd64.rock \
          docker-daemon:consul:v1.19.2
      - name: Start Consul container
        run: |
          docker run --name consul -p 8500:8500 -d consul:v1.19.2 exec consul agent -dev -client=0.0.0.0
      - name: Query Consul API
        run: |
          sleep 60
          if [[ "$(curl -k -s -o /dev/null -w "%{http_code}" http://localhost:8500/v1/agent/self)" != "200" ]]
          then
            exit 1
          fi


